import type { StatCard, User, RecentActivity, ChartDataPoint } from '@/types';

export const statCards: StatCard[] = [
  {
    id: '1',
    title: 'Total Revenue',
    value: '$84,245',
    change: 12.5,
    changeLabel: 'vs last month',
    icon: 'DollarSign',
    color: 'indigo',
  },
  {
    id: '2',
    title: 'Active Users',
    value: '12,847',
    change: 8.2,
    changeLabel: 'vs last month',
    icon: 'Users',
    color: 'emerald',
  },
  {
    id: '3',
    title: 'New Orders',
    value: '3,421',
    change: -3.1,
    changeLabel: 'vs last month',
    icon: 'ShoppingCart',
    color: 'amber',
  },
  {
    id: '4',
    title: 'Conversion Rate',
    value: '4.63%',
    change: 1.8,
    changeLabel: 'vs last month',
    icon: 'TrendingUp',
    color: 'rose',
  },
];

export const revenueData: ChartDataPoint[] = [
  { name: 'Jan', value: 42000, prev: 35000 },
  { name: 'Feb', value: 38000, prev: 32000 },
  { name: 'Mar', value: 55000, prev: 47000 },
  { name: 'Apr', value: 49000, prev: 41000 },
  { name: 'May', value: 63000, prev: 52000 },
  { name: 'Jun', value: 71000, prev: 58000 },
  { name: 'Jul', value: 68000, prev: 61000 },
  { name: 'Aug', value: 79000, prev: 65000 },
  { name: 'Sep', value: 84000, prev: 72000 },
  { name: 'Oct', value: 91000, prev: 78000 },
  { name: 'Nov', value: 87000, prev: 81000 },
  { name: 'Dec', value: 95000, prev: 84000 },
];

export const trafficData: ChartDataPoint[] = [
  { name: 'Mon', value: 3200 },
  { name: 'Tue', value: 4100 },
  { name: 'Wed', value: 3800 },
  { name: 'Thu', value: 5200 },
  { name: 'Fri', value: 4700 },
  { name: 'Sat', value: 3100 },
  { name: 'Sun', value: 2800 },
];

export const categoryData: ChartDataPoint[] = [
  { name: 'Electronics', value: 35 },
  { name: 'Clothing', value: 25 },
  { name: 'Food', value: 20 },
  { name: 'Books', value: 12 },
  { name: 'Other', value: 8 },
];

export const users: User[] = [
  {
    id: '1',
    name: 'Alice Johnson',
    email: 'alice@example.com',
    role: 'Admin',
    status: 'active',
    avatar: 'AJ',
    joinedDate: '2023-01-15',
    lastSeen: '2 min ago',
  },
  {
    id: '2',
    name: 'Bob Smith',
    email: 'bob@example.com',
    role: 'Editor',
    status: 'active',
    avatar: 'BS',
    joinedDate: '2023-03-22',
    lastSeen: '1 hr ago',
  },
  {
    id: '3',
    name: 'Carol White',
    email: 'carol@example.com',
    role: 'Viewer',
    status: 'inactive',
    avatar: 'CW',
    joinedDate: '2023-05-10',
    lastSeen: '3 days ago',
  },
  {
    id: '4',
    name: 'David Brown',
    email: 'david@example.com',
    role: 'Editor',
    status: 'pending',
    avatar: 'DB',
    joinedDate: '2023-07-04',
    lastSeen: '5 hr ago',
  },
  {
    id: '5',
    name: 'Eva Martinez',
    email: 'eva@example.com',
    role: 'Admin',
    status: 'active',
    avatar: 'EM',
    joinedDate: '2023-08-19',
    lastSeen: '30 min ago',
  },
  {
    id: '6',
    name: 'Frank Lee',
    email: 'frank@example.com',
    role: 'Viewer',
    status: 'active',
    avatar: 'FL',
    joinedDate: '2023-09-01',
    lastSeen: '2 days ago',
  },
  {
    id: '7',
    name: 'Grace Kim',
    email: 'grace@example.com',
    role: 'Editor',
    status: 'inactive',
    avatar: 'GK',
    joinedDate: '2023-10-11',
    lastSeen: '1 week ago',
  },
  {
    id: '8',
    name: 'Henry Wilson',
    email: 'henry@example.com',
    role: 'Viewer',
    status: 'pending',
    avatar: 'HW',
    joinedDate: '2023-11-05',
    lastSeen: '4 days ago',
  },
];

export const recentActivity: RecentActivity[] = [
  {
    id: '1',
    user: 'Alice Johnson',
    action: 'created',
    target: 'New Campaign',
    time: '2 min ago',
    type: 'create',
  },
  {
    id: '2',
    user: 'Bob Smith',
    action: 'updated',
    target: 'User Permissions',
    time: '15 min ago',
    type: 'update',
  },
  {
    id: '3',
    user: 'Eva Martinez',
    action: 'exported',
    target: 'Monthly Report',
    time: '1 hr ago',
    type: 'export',
  },
  {
    id: '4',
    user: 'David Brown',
    action: 'logged in',
    target: 'Dashboard',
    time: '2 hr ago',
    type: 'login',
  },
  {
    id: '5',
    user: 'Carol White',
    action: 'deleted',
    target: 'Old Backup',
    time: '3 hr ago',
    type: 'delete',
  },
  {
    id: '6',
    user: 'Frank Lee',
    action: 'created',
    target: 'Support Ticket #2891',
    time: '5 hr ago',
    type: 'create',
  },
];
